apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.db.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.db.name }}
spec:
  replicas: {{ .Values.db.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.db.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.db.name }}
    spec:
      containers:
      - name: postgres
        image: {{ .Values.db.image }}
        env:
        - name: POSTGRES_USER
          value: {{ .Values.db.postgresUser }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.db.postgresPassword }}
        ports:
        - containerPort: {{ .Values.db.containerPort }}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
      volumes:
      - name: db-data
        emptyDir: {}
