apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.db.name }}
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: {{ .Values.db.name }}
