apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voting-app-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /vote
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.vote.name }}
            port:
              number: {{ .Values.vote.servicePort }}
      - path: /result
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.result.name }}
            port:
              number: {{ .Values.result.servicePort }}
      - path: /argocd
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.result.name }}
            port:
              number: {{ .Values.result.servicePort }}
