apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.result.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.result.name }}
spec:
  type: ClusterIP
  ports:
    - name: result-service
      port: 8081
      targetPort: {{ .Values.result.containerPort }}
    #   nodePort: 31001
  selector:
    app: {{ .Values.result.name }}
