apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.result.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.result.name }}
spec:
  replicas: {{ .Values.result.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.result.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.result.name }}
    spec:
      containers:
        - name: {{ .Values.result.name }}
          image: {{ .Values.result.image }}
          ports:
            - containerPort: {{ .Values.result.containerPort }}
              name: {{ .Values.result.name }}
