apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.vote.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.vote.name }}
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: {{ .Values.vote.containerPort }}
  selector:
    app: {{ .Values.vote.name }}
