apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voting-app-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sharhan-alhassan/example-voting-app.git
    targetRevision: HEAD
    path: voting-app
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: voting-app
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
